name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      release:
        description: 'Type `full speed ahead` in order to release'
        default: 'no release'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Cache Gradle
      uses: actions/cache@v2
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-${{ hashFiles('gradle') }}
    - name: Build
      run: ./gradlew build
    - name: Upload test reports
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: build/reports/tests
    - name: Release
      if: github.event.inputs.release == 'full speed ahead'
      env:
        atlassian_private_username: ${{ secrets.ATLASSIAN_PRIVATE_USERNAME }}
        atlassian_private_password: ${{ secrets.ATLASSIAN_PRIVATE_PASSWORD }}
      run: |
        ./gradlew release
        ./gradlew publish
